title: Ploomber Cloud documentation
author: Ploomber
logo: logo.png

execute:
  execute_notebooks: force

repository:
  url: https://github.com/ploomber/doc
  path_to_book: doc
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
